<?php /**@var Catalog $block*/

use Kvitny\Home\Block\Catalog;

$categories = $block->getCategories();
?>
<section class="catalog__section">
    <h2 class="section__title">Catalog</h2>
    <div class="catalog__grid">
        <?php foreach ($categories as $category): ?>
            <?php if($category->getId() != 2 && $category->getId() != 1): ?>
                <a href="<?= $category->getUrl() ?>" >
                    <div class="catalog__card" style="background: url('<?= $category->getImageUrl() ?>')">
                        <div class="card__footer">
                            <span class="card__title"><?= __($category->getName()); ?></span>
                        </div>
                    </div>
                </a>
            <?php endif ?>
        <?php endforeach ?>
    </div>
</section>
<script type="text/x-magento-init">
  {
     "*": {
         "catalogCarousel": {
            "wrapper": ".catalog__grid"
         }
     }
  }
</script>
