<?php
/** @var BouquetListing $block */

use Kvitny\BouquetEntity\Block\BouquetListing;

$bouquetCollection = $block->getBouquetCollection();
?>
<h1 class="title">Bouquets</h1>
<div class="products wrapper grid products-grid">
    <ol class="products list items product-items">
        <?php foreach ($bouquetCollection as $bouquet): ?>
            <li class="item product product-item">
                <div class="product-item-info" id="product-item-info" data-container="product-grid">
                    <a href="<?= $block->getDetailsUrl($bouquet) ?>"
                       class="product photo product-item-photo"
                       tabindex="-1">
                                <span class="product-image-container" style="width: 240px;">
                                    <span class="product-image-wrapper">
                                        <img class="product-image-photo" src="<?= $block->getImage($bouquet) ?>"
                                             loading="lazy" width="240" height="300"
                                             alt="<?= $bouquet->getBouquetName() ?>">
                                    </span>
                                </span>
                    </a>
                    <div class="product details product-item-details">
                        <strong class="product name product-item-name">
                            <a class="product-item-link" href="<?= $block->getDetailsUrl($bouquet) ?>">
                                <?= $bouquet->getBouquetName() ?> </a>
                        </strong>
                    </div>
                </div>
            </li>
        <?php endforeach; ?>
    </ol>
</div>
