<?php
/** @var Banner $block */

use Kvitny\Banner\Block\Widget\Banner;

?>
<section class="banner" style="background-image: url('<?= $block->getImage() ?>')">
    <div class="banner__text">
        <?php if($title = $block->getTitle()): ?>
            <h1 class="banner__title"><?= $title ?></h1>
        <?php endif; ?>

        <?php if($subtitle = $block->getSubtitle()): ?>
            <h4 class="banner__descript"><?= $subtitle ?></h4>
        <?php endif; ?>

        <?php if($block->hasOrderButton()): ?>
            <button class="button order__button"><span><?= __("Order") ?></span></button>
        <?php endif; ?>
    </div>
</section>
