<?php
/** @var \Kvitny\Catalog\Block\Widget\BenefitsBanner $block */

/**
 * @var Escaper $escaper
 * @var SecureHtmlRenderer $secureRenderer
 */

use Magento\Catalog\Block\Product\ReviewRendererInterface;
use Magento\Framework\App\ActionInterface;
use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;
use Magento\Catalog\ViewModel\Product\Listing\PreparePostData;
?>
<section class="banner" style="background-image: url('<?= $block->getBannerImage() ?>')">
    <div class="banner__text">
        <?php if ($title = $block->getStoryTitle()): ?>
            <h1 class="banner__title"><?= $title ?></h1>
        <?php endif; ?>

        <?php if ($storytext = $block->getStoryText()): ?>
            <h4 class="banner__descript"><?= $storytext  ?></h4>
        <?php endif; ?>
        <div>
            <?php if ($benefits = $block->getBenefits()): ?>
                <?= htmlspecialchars_decode($benefits) ?>
            <?php endif; ?>
        </div>
    </div>
    <div class="products wrapper grid products-grid">
        <ol class="products list items product-items">
            <?php $_item = $block->getCurrentProduct() ?>
            <li class="item product product-item"
                id="product-item_<?= /* @noEscape */
                $_item->getId() ?>">
                <div class="product-item-info">
                    <a href="<?= $block->escapeUrl($_item->getProductUrl()) ?>"
                       class="product photo product-item-photo">
                        <img src="<?= $block->getProductImage($_item) ?>">
                    </a>
                    <div class="product details product-item-details">
                        <strong class="product name product-item-name"><a
                                class="product-item-link"
                                title="<?= $block->escapeHtmlAttr($_item->getName()) ?>"
                                href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>">
                                <?= $block->escapeHtml($_item->getName()) ?></a>
                        </strong>

                        <?= /* @noEscape */
                        $block->getProductPrice($_item) ?>
                        <?= $block->getReviewsSummaryHtml($_item, ReviewRendererInterface::SHORT_VIEW) ?>

                        <?php // phpcs:disable ?>
                        <div class="product actions product-item-actions">
                            <div class="actions-primary">
                                <?php if ($_item->isSaleable()): ?>
                                    <?php if (!$_item->getTypeInstance()->isPossibleBuyFromList($_item)): ?>
                                        <button
                                            class="action tocart primary"
                                            data-mage-init='{"redirectUrl": {"url": "<?= $block->escapeUrl($block->getAddToCartUrl($_item)) ?>"}}'
                                            type="button"
                                            title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>">
                                            <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                        </button>
                                    <?php else : ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_item) ?>
                                            <form data-role="tocart-form"
                                              data-product-sku="<?= $block->escapeHtmlAttr($_item->getSku()) ?>"
                                              action="<?= $block->escapeUrl($postParams['action']) ?>"
                                              method="post">
                                            <input type="hidden" name="product"
                                                   value="<?= $postParams['data']['product']; ?>">
                                            <input type="hidden"
                                                   name="<?= /* @noEscape */
                                                   ActionInterface::PARAM_NAME_URL_ENCODED ?>"
                                                   value="<?= $postParams['data'][ActionInterface::PARAM_NAME_URL_ENCODED]; ?>">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <button type="submit"
                                                    title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                    class="action tocart primary">
                                                <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                            </button>
                                        </form>
                                    <?php endif; ?>
                                <?php else: ?>
                                    <?php if ($_item->getIsSalable()): ?>
                                        <div class="stock available">
                                            <span><?= $block->escapeHtml(__('In stock')) ?></span>
                                        </div>
                                    <?php else: ?>
                                        <div class="stock unavailable">
                                            <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
                                        </div>
                                    <?php endif; ?>
                                <?php endif; ?>
                            </div>
                        </div>
                        <?php // phpcs:enable ?>
                    </div>
                </div>
            </li>
        </ol>
    </div>
</section>
